# Generated by Django 4.1 on 2022-09-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyWatchList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched', models.TextField()),
                ('title', models.TextField()),
                ('rating', models.FloatField()),
                ('release_date', models.TextField()),
                ('review', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='MovieList',
        ),
    ]
